### PR TITLE
build: Upgrade Node to v18.16.1

### LINKED ISSUE #118: Update Alberto packages and node version

### PR DESCRIPTION
**Pull request by stanleyjones**
Same as https://github.com/liftedinit/gwen/pull/57.

Closes #118 .

### CODE REVIEW

**Comment by stanleyjones** [comment]
@fmorency Is this PR sufficient to close #118 or do you want me to go through all the dependencies?

**Comment by stanleyjones** [comment]
Throwing this into draft while I review the CI failure.

**Review by fmorency — COMMENTED** [review]
@stanleyjones LGTM as a first step. Please update the dependencies as well after this is merged.

Re-request a review from me when CI is solved.

Thanks!

**Comment by stanleyjones** [comment]
CI problem resolved. There was a race condition in an integration test. Re-requesting reviews.

**Review by fmorency — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
