### PR TITLE
feat: Disable Hardware Authenticator identities for unsupported Networks

### LINKED ISSUE #135: Disable `Hardware Authenticator` entry if neighborhood doesn't support it
Some neighborhood, such as kvstore, dweb and compute, don't implement the `idstore` module. We should disable the ability to create/import `Hardware Authenticator` when such a neighborhood is selected.

We should also display a message if a neighborhood doesn't support the HSM feature.

@stanleyjones

### PR DESCRIPTION
**Pull request by stanleyjones**
See liftedinit/gwen#75

Closes #135

### CODE REVIEW

**Comment by stanleyjones** [comment]
Looking into CI failures. I think it's a package that was updated in `main` but not this branch.

**Comment by stanleyjones** [comment]
Okay, should look pretty similar to liftedinit/gwen#75. Reviews welcome.

**Review by fmorency — COMMENTED** [review]
LGTM.

@jgryffindor can we deploy in QA, please? Thanks!

**Comment by jgryffindor** [comment]
I'm getting the same result. The release is out in QA so if there aren't any new infra requirements for this feature then it's something in the release.

**Comment by fmorency** [comment]
@stanleyjones I don't think the issue I reported above is related to this PR. I will investigate.

Could you start working on #142 ?

**Comment by fmorency** [comment]
Fixed in https://github.com/liftedinit/alberto/pull/147

**Comment by fmorency** [comment]
Tested in QA, everything LGTM. Thanks @stanleyjones

**Review by fmorency — APPROVED** [review]

**Pull request merged**
